# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task',
            name='star_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_task',
            name='taskname',
            field=models.CharField(default='', max_length=32),
        ),
    ]
