# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0003_user_task_host_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='software',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
