# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0006_hostinfo_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_task',
            old_name='host_group',
            new_name='hosts',
        ),
    ]
