# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0013_user_task_softinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task',
            name='looked',
            field=models.BooleanField(default=False),
        ),
    ]
