# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0014_user_task_looked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_task',
            old_name='looked',
            new_name='acked',
        ),
    ]
