# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0017_test123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test123',
        ),
    ]
