# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0018_delete_test123'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='memory',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='vginfo',
            field=models.CharField(default='', max_length=64),
        ),
    ]
