# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0020_auto_20170704_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='memory',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='memory_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='memory_used',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
