# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mesos', '0022_auto_20170705_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='memory_free',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='memory_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='memory_used',
            field=models.IntegerField(default=0),
        ),
    ]
