# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlAduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('mysqluser', models.CharField(max_length=64)),
                ('mysqlhost', models.CharField(default='', max_length=16)),
                ('login_host', models.CharField(default='localhost', max_length=16)),
                ('pridate', models.DateTimeField(auto_now=True)),
                ('pri_database', models.CharField(default='', max_length=32)),
                ('pri_table', models.CharField(default='', max_length=32)),
                ('privilege', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('option', models.CharField(max_length=10)),
                ('mysqlhost', models.CharField(max_length=16)),
                ('mysqluser', models.CharField(max_length=64)),
                ('pridate', models.DateTimeField(auto_now_add=True)),
                ('pri_database', models.CharField(default='', max_length=32)),
                ('pri_table', models.CharField(default='', max_length=32)),
                ('privilege', models.CharField(max_length=48)),
            ],
        ),
    ]
