# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0002_sidinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softname', models.CharField(max_length=16)),
            ],
        ),
    ]
