# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0003_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidinfo',
            name='port',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidinfo',
            name='socketpath',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
