# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0004_auto_20170619_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostip_Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=16)),
                ('port', models.CharField(default='3306', max_length=6)),
            ],
        ),
    ]
