# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0006_sidinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidinfo',
            name='replpassword',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
