# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0007_sidinfo_replpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidinfo',
            name='data_size',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidinfo',
            name='result',
            field=models.BooleanField(default=False),
        ),
    ]
