# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0010_auto_20170622_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostip_port',
            name='port',
            field=models.IntegerField(default=3306),
        ),
        migrations.AlterField(
            model_name='sidinfo',
            name='port',
            field=models.IntegerField(),
        ),
    ]
