# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0011_auto_20170622_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidinfo',
            name='buffer_pool',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
