# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0012_sidinfo_buffer_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidinfo',
            name='project_name',
            field=models.CharField(default='CRM', max_length=32),
            preserve_default=False,
        ),
    ]
