# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0013_sidinfo_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidinfo',
            old_name='project_name',
            new_name='appname',
        ),
    ]
