# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_ansible', '0014_auto_20170705_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='vsersion',
            field=models.TextField(default=''),
        ),
    ]
