# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0001_initial'),
        ('hd_mysql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('login_user', models.CharField(max_length=32)),
                ('login_passwd', models.CharField(max_length=128)),
                ('bk_database', models.CharField(max_length=32)),
                ('bk_table', models.CharField(default='', max_length=32)),
                ('ct_shd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hd_mysql.Custom_Schedule')),
                ('period_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask')),
            ],
        ),
    ]
