# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mysql', '0002_schedule_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_info',
            name='hour_minute',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
