# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mysql', '0003_schedule_info_hour_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_info',
            name='login_passwd',
        ),
        migrations.RemoveField(
            model_name='schedule_info',
            name='login_user',
        ),
        migrations.RemoveField(
            model_name='schedule_info',
            name='port',
        ),
    ]
