# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mysql', '0004_auto_20170725_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_info',
            name='mysql_bk_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
