# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mysql', '0005_schedule_info_mysql_bk_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mysql_bk_name', models.CharField(max_length=32)),
                ('star_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('result', models.TextField()),
            ],
        ),
    ]
