# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mysql', '0006_schedule_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_res',
            name='status',
            field=models.CharField(default='\u6210\u529f', max_length=8),
            preserve_default=False,
        ),
    ]
