# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_mysql', '0007_schedule_res_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sql_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_name', models.CharField(max_length=32)),
                ('sql_handle', models.TextField()),
                ('arg_count', models.IntegerField(null=True)),
            ],
        ),
    ]
